### ISSUE TITLE
Error: No commit found for the ref master

### ISSUE THREAD

**Issue by nanigan** [JasonEtco/rss-to-readme#24]
I'm sure there's something I've configured incorrectly, but the scheduled build fails every night with the error

Error: No commit found for the ref master
✖  fatal     HttpError: No commit found for the ref master 
    at /home/runner/work/_actions/JasonEtco/rss-to-readme/v1/dist/index.js:19081:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by rlevchenko** [comment]
mine forks fine. changed v1 to v2, set a branch to main

```
name: Update readme with blog posts
on: 
  schedule:
    - cron: '00 11 * * *'
  push:
    branches: [ main ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2
        with:
          feed-url: https://rlevchenko.com/rss/
          max: 3
          readme-section: feed
          branch: main
          empty-commits: false
          template: "#### [{{ title }}]({{ link }}) \n*{{ pubDate }}*\n\n"
```
